"""Create formula column as unique

Revision ID: 2e056067ca41
Revises: bc3d4c5e556b
Create Date: 2024-01-30 12:44:21.620557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e056067ca41'
down_revision: Union[str, None] = 'bc3d4c5e556b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'materials', ['formula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='unique')
    # ### end Alembic commands ###
